### ISSUE TITLE
与 CocoaPods 兼容性问题

### ISSUE THREAD

**Issue by charsunny** [jpush/jmessage-ios-pod#1]
将JMessage加入到CocosPod并且
Podfile 里指定 use_frameworks! 时 (iOS 8 only 项目) 。  pod update 失败报错： [!] The 'Pods' target has transitive dependencies that include static binaries: ....
希望增加动态库的支持！很急 谢谢

**Comment by huangminlinux** [comment]
podfile 文件内容是什么？
